### PR TITLE
Create tar.gz package using maven

### PR DESCRIPTION
**Pull request by yanivmn**

### CODE REVIEW

**Comment by matzew** [comment]
cool.

I think it would be also good if we download the keyloak.js file (1.7.0.Final), istead of doing a reference to `/auth`:
https://github.com/aerogear/unifiedpush-admin-ui/blob/master/app/index.html#L159

**Comment by matzew** [comment]
@yanivmn I just realize that this, unfortunately, does no longer generate a JAR file

**Comment by yanivmn** [comment]
Why do you need a static content html/css/js to be packed as a jar file?

**Comment by matzew** [comment]
I just add the UI as a JAR, that way to the WAR file, using normal maven declaration

**Comment by yanivmn** [comment]
But you can publish this model as tar.gz and even unpack using maven dependency plugin.
if you need my assistance, please state a branch name and desired directory structure.

**Comment by matzew** [comment]
@yanivmn if you like, why not against the UPS master branch ? :-)

**Comment by yanivmn** [comment]
Please state your desired output? 
Extract tar.gz to war file during maven package cycle.?

**Pull request merged**
