### PR TITLE
(feat)Wizard: Set up variant

### PR DESCRIPTION
**Pull request by Aindriunannerb**
## Motivation
Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.redhat.com/browse/AEROGEAR-10219

## What
Create the third step of the wizard where a user can view the information and relevant code snippets of the newly created variant.
Currently the variant is not being passed correctly to the code snippets component and keeps giving an undefined error

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member

### CODE REVIEW

**Comment by secondsun** [comment]
@Aindriunannerb couple of things I noticed

1) When I created a variant in the wizard, clicking next doesn't dismiss the wizard but creates the Variant and Application. Is this the expected result while we get step 4 (sending a message) in?

2) When I pressed next a blank or invalid variant, I got a stack trace screen. I was expecting some validation errors. Are those still in progress?

**Comment by secondsun** [comment]
I noticed there were a few errors in the console. One was about key properties being missing in one of the lists (I think it is actually the application list) and the other was about nested form components. Can you see if either of those are caused in this PR?

**Comment by Aindriunannerb** [comment]
> @Aindriunannerb couple of things I noticed
> 
> When I created a variant in the wizard, clicking next doesn't dismiss the wizard but creates the Variant and Application. Is this the expected result while we get step 4 (sending a message) in?
Yes, sorry I should have mentioned that, I felt it was suitable to leave the wizard there until step 4 was added


> When I pressed next a blank or invalid variant, I got a stack trace screen. I was expecting some validation errors. Are those still in progress?
Massimos work with the validator was not fully implemented when I created the PR and we had discussed creating an issue adding the validation later. I can  add it now though

**Comment by secondsun** [comment]
No, was clicking the submit button on the variant form.

Even if validation isn't implemented, it shouldn't crash the app.

**Pull request merged**
