### PR TITLE
Add i18n support

### PR DESCRIPTION
**Pull request by tagoh**
The changes that this PR contains was originally reported as https://github.com/aerogear/aerogear-unifiedpush-server/pull/840 and revised because the repo was separate now.

I didn't add a configuration to change the language intentionally. you could refer this document to load the translation on demand: https://angular-gettext.rocketeer.be/dev-guide/lazy-loading/

### CODE REVIEW

**Comment by matzew** [comment]
do we really want this ?

**Comment by matzew** [comment]
@josemigallas @david-martin @pb82  any comments ?

**Comment by tagoh** [comment]
@pb82 Yes, it is picking up the targeted strings to be translated and generating JSON files to load translations. just needing to decide to allow users to see the translated strings whether UI has a preference to change the language or simply refer the brower acceptable language.
For testing this change, you originally need to prepare any translations though, you could work around it by settings the language to non-English and then set debug flag on angular-gettext. you'll see "[MISSING]:"  prefix on string then. see https://angular-gettext.rocketeer.be/dev-guide/configure/

**Comment by danielpassos** [comment]
Hey @tagoh sorry to leave it open for so long, but UPS UI is gonna be redesigned from scratch so, I'm going to close it. Thanks for your contribution

**Pull request closed without merging**
