### PR TITLE
Keycloak 3.2.1 bundle

### PR DESCRIPTION
**Pull request by matzew**
using latest KC final release

### CODE REVIEW

**Comment by matzew** [comment]
@lholmquist mind taking a qiuick look ?

**Comment by lholmquist** [comment]
@matzew that should be fine to pull in the latest.  Not sure if there has been updates to the api for authenticating though

**Comment by matzew** [comment]
@lholmquist works just fine, when updating the server and the adapter ;-)

**Comment by lholmquist** [comment]
👍

**Pull request merged**
